# Basic CI setup: Lint with ruff, run tests with pytest
name: Testing and Linting

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    name: Run tests
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5
      - uses: astral-sh/setup-uv@v6
      - run: uv run --dev pytest